# Generated by Django 2.0.6 on 2018-06-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20180617_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('call', 'type')},
        ),
    ]
